### PR TITLE
Drivetrain Fix

### PR DESCRIPTION
**Pull request by ammenzl7**
Fixes drivetrain mismatch
Adds NavX libraries
Adds preliminary gyro values to the SmartDashboard (isConnected, Yaw, Pitch, Roll)

### CODE REVIEW

**Comment by ammenzl7** [comment]
This is ready for review, I've removed the unnecessary and untested code that was tacked along for the ride. @abcurrie & @Granto1 Please submit a review for this, preferably before the meeting tomorrow so we can have a clean, working base branch for incoming work. I can go over how to merge master into everyone's local branch at the meeting tomorrow.

**Review by Granto1 — APPROVED** [review]
Looks good. I cannot attend the meeting tomorrow, am participating in a hackathon, but will do further reading into version control when time allows.

**Comment by Granto1** [comment]
Question: Currently both pull requests in the repository are approved and able to merge. Based on previous comments, ought the settings be adjusted to reflect the necessity of a Mentor + Student Lead review + approval? Or should one review + approval suffice to merge changes?

**Comment by ammenzl7** [comment]
We can have a discussion about what kind of approvals are needed for PRs, we have no agreed-upon standard on the team yet. I haven't had time to look into setting up groups just yet. We could have it set up where 1 review is needed to merge changes, or we can set it up where one student and one mentor both need to approve before changes can be merged. Regardless, I'll probably be making the groups. I'd like to talk it over with the mentors and students before adjusting the number of required approvals. For now, I think the way we have it is fine.

**Pull request merged**
