### PR TITLE
Bobo gyro

### PR DESCRIPTION
**Pull request by abcurrie**

### CODE REVIEW

**Review by Granto1 — APPROVED** [review]

**Comment by ammenzl7** [comment]
What is the purpose of this pull request? Does it have to do with Bobo's gyro work, or is this just some housekeeping regarding the TankDrive naming convention and NavX implementation?

**Review by Granto1 — COMMENTED** [review]
As of today, the pull request pertains to library updates + TankDrive naming convention + based on Wednesday night commit, Gyro is in working order.

**Comment by ammenzl7** [comment]
For future reference, pull requests are supposed to be for singular changes, not for multiple different changes that have no real connection. The pull request was fine to be merged until the gyro stuff was added. It adds unnecessary complexity to the pull request.

Really what should've happened was that the drivetrain & library updates should've been done on a separate branch from this, so that when Bobo pushed his changes it didn't affect a PR for something completely different.

I'm going to mess around with the commits to try to get this back on track.

Also, it's good practice to add a description to the PR when creating it.

**Comment by ammenzl7** [comment]
Closing this pull request, see https://github.com/The-Charge/Spike2023/pull/5

**Pull request closed without merging**
